---
 - name: "service status"
   hosts: web
   tasks:
     - name: sshd
       service: name=sshd state=started
       tags: sshd
     - name: httpd
       service: name=httpd state=started
       tags: httpd
     - name: vsftpd
       service: name=vsftpd state=started
       tags: vsftpd
     - name: samba
       service: name=smb state=started
       tags: smb
     - name: nfs
       service: name=nfs state=started
       tags: nfs
     - name: autofs
       service: name=autofs state=started
       tags: autofs
     - name: ntpd
       service: name=ntpd state=started
       tags: ntpd
     - name: rsyslog
       service: name=rsyslog state=started
       tags: rsyslog
